services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=cv-store'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
      - 'driver-class-name: org.postgresql.Driver'
    labels:
      - 'org.springframework.boot.service-connection=postgres'
    ports:
      - '5432:5432'
